version: '3.2'
services:
  quizz:
    build: ./
    ports:
      - "8000"
    environment:
      - REDIS_HOST=redis
    volumes:
      - "./:/usr/src/app"
    labels:
      - "traefik.backend=quizz"
      - "traefik.frontend.rule=Host:192.168.1.24;"
    command: sh ./startup.sh

  static:
    image: nginx
    ports:
      - "80"
    volumes:
      - "./static:/usr/share/nginx/html/static"
      - "./nginx.conf:/etc/nginx/conf.d/default.conf"
    labels:
      traefik.port: "80"
      traefik.backend: "static"
      traefik.frontend.rule: "Host:192.168.1.24;PathPrefix:/static"

  pgquizz:
    image: postgres:10.6
    ports:
      - "5434"
    environment:
      - POSTGRES_USER=quizz
      - POSTGRES_DB=quizz
      - POSTGRES_PASSWORD=nopass
    volumes:
      - "./pgVolume:/var/lib/postgresql/data"

  redis:
    image: "redis"
    ports:
      - "6379:6379"

  traefik:
    image: containous/traefik:latest
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - "./traefik.toml:/etc/traefik/traefik.toml"
      - "/var/run/docker.sock:/var/run/docker.sock"