# Generated by Django 2.1.4 on 2019-01-04 14:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quizzer', '0002_auto_20190104_1432'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='round',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='quizzer.Round'),
        ),
        migrations.AlterField(
            model_name='question',
            name='type',
            field=models.CharField(choices=[('txt', 'texte'), ('img', 'image'), ('vid', 'video')], default='txt', max_length=3),
        ),
    ]
