# Generated by Django 2.1.4 on 2019-01-04 16:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quizzer', '0004_quizzerstate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizzerstate',
            name='question',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='quizzer.Question'),
        ),
    ]
