# Generated by Django 2.1.4 on 2019-01-04 17:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quizzer', '0006_auto_20190104_1644'),
    ]

    operations = [
        migrations.AddField(
            model_name='round',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='quizzerstate',
            name='round',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='quizzer.Round'),
        ),
    ]
