# Generated by Django 2.1.4 on 2019-01-04 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzer', '0007_auto_20190104_1746'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['order', 'pk']},
        ),
        migrations.AlterModelOptions(
            name='round',
            options={'ordering': ['order', 'pk']},
        ),
        migrations.AlterField(
            model_name='question',
            name='answer',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
